#!/bin/bash 

#export WORKLOADS="fileserver varmail webproxy webserver"
WORKLOADS="fileserver"

LOGDIR="log"

LOGFILE="${LOGDIR}/filebench"

#. mount_fs /dev/monetaa

#. xdd_setup_cache 
for WORKLOAD in ${WORKLOADS}; do
	echo "Filebench workload ${WORKLOAD}"
	echo "Starting run"

	sync
	sleep 2
	~/benchmarks/filebench-1.4.9.1/filebench -f filebench_models/${WORKLOAD}.f >> ${LOGFILE} 

done

