#!/bin/bash 

# Run filebench on disk, flashcache and mcache 

export WORKLOADS="fileserver varmail webproxy webserver videoserver"

#for WORKLOAD in ${WORKLOADS}; do
#	echo "Filebench workload ${WORKLOAD} running on disk"
#	. filebench_disk 	
#done
#
#for WORKLOAD in ${WORKLOADS}; do
#	echo "Filebench workload ${WORKLOAD} running with flashcache"
#	. filebench_flashcache
#done

export LOG="filebench_bankshot2"

#. xdd_setup_cache 
for WORKLOAD in ${WORKLOADS}; do
	echo "Filebench workload ${WORKLOAD} running with bankshot2"
	. filebench_bankshot2 

done
