#!/bin/bash 

. config_common 

export BACKING_STORE="sdb sdc"
export SCHEDULER=noop
LOGFILE="${LOGDIR}/filebench_disk"

# stats are saved in .stats file 
STATSFILE="${LOGFILE}.stats"

. config_backing_store

. setup_raid

. setup_ramdisk

. mount_fs /dev/md0 

echo "----------------PRERUN---------------------" > ${STATSFILE}
. system_stats
. disk_stats 

sudo /x/SC2010/scripts/flush_cache >> ${QUIET} 

${BEE3HOME}/Workloads/filebench-1.4.9.1/filebench -f filebench_models/${WORKLOAD}.f >> ${LOGFILE} 2>${QUIET}

echo "----------------POSTRUN---------------------" >> ${STATSFILE}
. system_stats
. disk_stats
