#!/bin/bash 

LOGDIR="log"

LOGFILE="${LOGDIR}/filebench_bankshot2"

# stats are saved in .stats file 
STATSFILE="${LOGFILE}"

#. mount_fs /dev/monetaa

echo "Starting run"

sync
sleep 2
./run_bankshot2 ~/filebench-1.4.9.1/filebench -f filebench_models/${WORKLOAD}.f >> ${LOGFILE} 

