#!/bin/bash 

LOGDIR="log"

LOGFILE="${LOGDIR}/iozone"

#. mount_fs /dev/monetaa

#. xdd_setup_cache 
echo "IoZone running"
echo "Starting run"

sync
sleep 2
~/benchmarks/iozone3_424/src/current/iozone -f /mnt/ramdisk1/test1 -a -w -+N -y 1k -q 4m -s 1g -i 0 -i 1 -i 2 -i 3 -i 4 -i 5 | tee ${LOGFILE} 
#~/benchmarks/iozone3_424/src/current/iozone -f /mnt/ramdisk/test1 -a -w -r 4k -s 1g -i 0 -i 1  


