#!/bin/bash 

#export WORKLOADS="fileserver varmail webproxy webserver"
CYCLES="1"
WORKLOADS="fileserver"

#THREADS="1 2 4 8 16 100"
THREADS="2"
#SIZES="16k 128k 512k 2m 4m"
SIZES="2m"

LOGDIR="log/filebench/bankshot2"

for WORKLOAD in ${WORKLOADS}; do
for THREAD in ${THREADS}; do
for FILESIZE in ${SIZES}; do
for CYCLE in ${CYCLES}; do
	echo "Filebench workload ${WORKLOAD} running with bankshot2"
	echo "Cycle ${CYCLE}, thread ${THREAD}"
	echo "Starting run"
	export LOGFILE="${LOGDIR}/${WORKLOAD}_${THREAD}_${FILESIZE}_${CYCLE}"
	echo "Log file: ${LOGFILE}"
	echo "===============================================================" >> ${LOGFILE}
	echo "===============================================================" >> ${LOGFILE}
	echo "===============================================================" >> ${LOGFILE}
	echo "===============================================================" >> ${LOGFILE}

	rm -rf /mnt/ramdisk/logfiles
	rm -rf /mnt/ramdisk/bigfileset

	~/bankshot2/kernel/clear_cache
	sleep 1
	~/bankshot2/kernel/clear_cache
	sleep 1

	sync
	sleep 2
	export TARGET_FILE="${WORKLOAD}/${WORKLOAD}_${THREAD}_${FILESIZE}.f"
	echo "Target file: ${TARGET_FILE}"
	. execute_filebench_bankshot2
	cat ${LOGFILE} |grep "Summary"

done
done
done
done

